### ISSUE TITLE
Wrong render when using ruby if after expression

### ISSUE THREAD

**Issue by wildjcrt** [trailblazer/cells-erb#5]
I wrote a demo to show this problem.

Check out https://github.com/wildjcrt/test-erbse and open http://localhost:3000/articles

For ex:
```ruby
<p>
  show @foo: <%= @foo if true %>
</p>
```
It will generate:
```html
</p>
```

**Comment by clifff** [comment]
I'm seeing this same kind of problem. From what I can tell, it's Erbse not properly handling statement modifiers. In my particular case, it was manifesting as a Syntax error, like #6. When I commented out a line similar to `<%= 'string' if x %>` it started behaving as expected again.

**Comment by george-carlin** [comment]
I'm having the same issue - upgrading to cells-erb 0.1.0 completely broke my views. Here's how e.g. the top of my sign in page looked before:

<img width="1030" alt="screen shot 2017-01-17 at 18 23 36" src="https://cloud.githubusercontent.com/assets/2656485/22034382/0733e55e-dce4-11e6-917e-15f517c86ef9.png">

That's with cells-erb 0.0.9 and erbse 0.0.2. Somewhere along the line while upgrading to trailblazer 2, my versions got bumped to cells-erb 0.1.0 and erbse 0.1.1, and this happens:

<img width="980" alt="screen shot 2017-01-17 at 18 39 04" src="https://cloud.githubusercontent.com/assets/2656485/22034794/502d7f62-dce5-11e6-830b-c9ae255c30ea.png">

Looks like it's this particular line of code that's causing things to break:

        <div class="small-logo" <%= raw('style="padding-left: 20px"') if pad_logo? %>>

But that's just one of many examples within my code base; it looks like I get similar problems every time I use a trailing `if` within a `<%= ... %>`. No idea if this is a problem with cells-erb or with erbse.

For now, the solution for me was to **downgrade back to cells 0.0.9**.

**Comment by apotonick** [comment]
Will look into it!

**Comment by george-carlin** [comment]
Has there been any progress on this?

**Comment by ncreuschling** [comment]
_nudge_

**Comment by apotonick** [comment]
This is an Erbse gem problem. That gem has 100 lines of code, it's the perfect occasion for some OSS deep dive!

**Comment by ncreuschling** [comment]
May I politely suggest: tilt supports [Erubi](https://github.com/jeremyevans/erubi) out of the box.

**Comment by apotonick** [comment]
Erubi doesn't support a clean capture the way we do it in Erbse. If it does, I'm happy to ditch this gem.

**Comment by aiomaster** [comment]
@apotonick Isn't it a clean capture? https://github.com/jeremyevans/erubi#capturing
What do you think is missing there?

**Comment by apotonick** [comment]
I don't know how Jerry implemented it. In Erbse, the captures block is literally evaluated and simply *returned*, there is no output buffer or any global state. That's why it works so well with form builders, etc. It took me weeks to get to the point where I realized that all other formats do it wrong by supporting the idea of an output buffer and state - this screws up when you have nested view components.

If you can find out how Erubi does the capturing, we can reconsider!

**Comment by aiomaster** [comment]
@apotonick Ok I tried to hack inline or postfix conditionals support to erbse. Can you have a look, please?

**Comment by apotonick** [comment]
Fixed in Erbse 0.1.2. :fire_engine:
